services:
  pgbouncer:
    image: edoburu/pgbouncer:1.22.1-p0
    restart: always
    environment:
      DB_HOST: "pgm-uf6v3p8951004780.pg.rds.aliyuncs.com"
      DB_PORT: "5432"
      DB_USER: "tg_user"
      DB_PASSWORD: "${TG_DB_PASSWORD}"
      DB_NAME: "trade_guide"
      POOL_MODE: "transaction"
      DEFAULT_POOL_SIZE: "20"
      MAX_CLIENT_CONN: "500"
    networks: [appnet]

  postgrest:
    image: postgrest/postgrest:v12.2.3
    restart: always
    environment:
      PGRST_DB_URI: "postgres://tg_user:${TG_DB_PASSWORD}@pgbouncer:5432/trade_guide"
      PGRST_DB_SCHEMA: "public"
      PGRST_DB_ANON_ROLE: "anon"
      PGRST_DB_POOL: "20"
      PGRST_DB_PREPARED_STATEMENTS: "false"
      PGRST_SERVER_POOL_SIZE: "20"
      PGRST_LOG_LEVEL: "info"
      PGRST_OPENAPI_SERVER_PROXY_URI: "https://api.trade-calculator.top"
    depends_on: [pgbouncer]
    networks: [appnet]

  nginx:
    image: nginx:1.27-alpine
    restart: always
    volumes:
      - /srv/trade-guide/dist:/usr/share/nginx/html:ro
      - /srv/trade-guide/deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /srv/trade-guide/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    networks: [appnet]

networks:
  appnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.66.0.0/24